// Seed data representing crawled/searched posts from families looking for FO, MAS, and FAM spots
const initialPostings = [
  {
    id: "post-1",
    type: "MAS",
    status: "New",
    priority: "High",
    date: "2026-05-27",
    region: "Île-de-France",
    title: "Recherche place MAS en urgence - Thomas, 22 ans (Polyhandicap)",
    description: "Bonjour, nous recherchons activement une place en Maison d'Accueil Spécialisée (MAS) en Île-de-France pour notre fils Thomas, 22 ans. Il présente un polyhandicap avec dépendance totale pour les actes de la vie quotidienne. Notification MDPH en cours de validité. Situation d'épuisement familial sévère.",
    handicap: "Polyhandicap",
    age: 22,
    familyMember: "Thomas",
    contactName: "Valérie Gauthier (Mère)",
    contactPhone: "+33 6 89 54 32 10",
    contactEmail: "valerie.gauthier.pro@gmail.com",
    contactSocial: "https://www.facebook.com/groups/polyhandicap.france/posts/78912345",
    notes: "Dossier MDPH complet avec orientation MAS validée par la CDAPH. Contact établi par mail le 27/05."
  },
  {
    id: "post-2",
    type: "FAM",
    status: "Contacted",
    priority: "Medium",
    date: "2026-05-26",
    region: "Auvergne-Rhône-Alpes",
    title: "Demande de place en FAM - Lucas, 29 ans (Autisme sévère)",
    description: "Recherche un Foyer d'Accueil Médicalisé (FAM) spécialisé autisme dans la région lyonnaise ou départements limitrophes. Lucas a 29 ans, présente des troubles du comportement modérés et nécessite un encadrement structuré (méthodes TEACCH/ABA). Actuellement en amendement Creton dans son IME actuel.",
    handicap: "Autisme (TSA)",
    age: 29,
    familyMember: "Lucas",
    contactName: "Jean-Pierre Bernard (Père)",
    contactPhone: "+33 4 72 33 44 55",
    contactEmail: "jp.bernard.lyon@wanadoo.fr",
    contactSocial: "https://www.facebook.com/groups/autisme.rhone/posts/55642398",
    notes: "Appelé le père le 28/05. Il a déjà envoyé 4 dossiers dans le 69. Très inquiet de la fin de l'amendement Creton."
  },
  {
    id: "post-3",
    type: "FO",
    status: "New",
    priority: "Medium",
    date: "2026-05-25",
    region: "Hauts-de-France",
    title: "Recherche Foyer de Vie / Foyer Occupationnel - Sarah, 31 ans",
    description: "Ma sœur Sarah, 31 ans, présente une déficience intellectuelle moyenne avec une bonne autonomie physique. Elle aime les activités manuelles, artistiques et le jardinage. Nous recherchons un Foyer Occupationnel (FO) ou Foyer de Vie dans le Nord (59) ou Pas-de-Calais (62) pour la rentrée prochaine.",
    handicap: "Déficience Intellectuelle",
    age: 31,
    familyMember: "Sarah",
    contactName: "Claire Lemaire (Sœur)",
    contactPhone: "+33 7 88 12 34 56",
    contactEmail: "claire.lemaire59@outlook.com",
    contactSocial: "https://forum.doctissimo.fr/sante/handicap/recherche-foyer-vie-nord-sujet_1289_1.htm",
    notes: "Sarah est actuellement en accueil de jour 2 jours par semaine. Elle souhaite un hébergement complet."
  },
  {
    id: "post-4",
    type: "MAS",
    status: "Waiting List",
    priority: "High",
    date: "2026-05-24",
    region: "Provence-Alpes-Côte d'Azur",
    title: "Recherche MAS suite à retour d'institution en Belgique - Antoine, 25 ans",
    description: "Antoine rentre de Belgique fin juin. Il a une orientation MAS accordée par la MDPH du Var (83). Il présente des troubles envahissants du développement associés à une épilepsie pharmaco-résistante. Recherche place disponible ou accueil temporaire de toute urgence.",
    handicap: "TED & Épilepsie",
    age: 25,
    familyMember: "Antoine",
    contactName: "Michel Dubois (Père)",
    contactPhone: "+33 6 45 78 90 12",
    contactEmail: "dubois.michel.var@free.fr",
    contactSocial: "https://www.facebook.com/groups/retour-belgique-handicap/posts/9912883",
    notes: "Inscrit sur liste d'attente à la MAS 'La Source' (Toulon). Relancer le directeur en juin."
  },
  {
    id: "post-5",
    type: "FO",
    status: "New",
    priority: "Low",
    date: "2026-05-23",
    region: "Nouvelle-Aquitaine",
    title: "Recherche Foyer d'Hébergement (FH/FO) - Julie, 35 ans (Trisomie 21)",
    description: "Julie a 35 ans et travaille à mi-temps en ESAT. Elle recherche un Foyer d'Hébergement ou Foyer de Vie en Gironde (33) proche des transports en commun pour développer son autonomie de vie en dehors du domicile familial.",
    handicap: "Trisomie 21",
    age: 35,
    familyMember: "Julie",
    contactName: "Hélène Martin (Mère)",
    contactPhone: "+33 5 56 12 87 65",
    contactEmail: "helene.martin.bordeaux@orange.fr",
    contactSocial: "https://www.facebook.com/groups/trisomie21.gironde/posts/10293847",
    notes: "Dossier d'admission déposé à l'association ADAEI. Julie est très motivée."
  },
  {
    id: "post-6",
    type: "FAM",
    status: "Interview Scheduled",
    priority: "High",
    date: "2026-05-22",
    region: "Occitanie",
    title: "Urgent: Recherche FAM après rupture de parcours - Alexandre, 28 ans",
    description: "Alexandre présente des séquelles de traumatisme crânien avec des troubles cognitifs et mnésiques importants nécessitant un accompagnement psycho-éducatif et une surveillance médicale régulière. Suite à la fermeture de sa structure d'accueil de jour, il se retrouve sans solution.",
    handicap: "Traumatisme Crânien",
    age: 28,
    familyMember: "Alexandre",
    contactName: "Dr. Sandrine Moreau (Tuteur / Médecin)",
    contactPhone: "+33 6 01 22 33 44",
    contactEmail: "sandrine.moreau.tuteur@pro-sante.fr",
    contactSocial: "https://www.linkedin.com/posts/sandrine-moreau-tuteur_handicap-traumatisme-cranien-fam-activity-71289389",
    notes: "Entretien planifié le 02/06 avec la directrice du FAM 'L'Horizon' à Montpellier."
  },
  {
    id: "post-7",
    type: "MAS",
    status: "New",
    priority: "High",
    date: "2026-05-21",
    region: "Grand Est",
    title: "Recherche MAS - Trouble du Spectre de l'Autisme très sévère - Hugo, 20 ans",
    description: "Bonjour, mon fils Hugo vient de fêter ses 20 ans. Il a de très gros troubles du comportement (auto et hétéro-agressivité). L'IME ne peut plus le garder au-delà de juillet. Orientation MAS confirmée par la MDPH du Bas-Rhin. Nous cherchons désespérément une structure adaptée.",
    handicap: "Autisme Sévère / TSA",
    age: 20,
    familyMember: "Hugo",
    contactName: "Nathalie Klein (Mère)",
    contactPhone: "+33 3 88 45 76 12",
    contactEmail: "nathalie.klein67@bbox.fr",
    contactSocial: "https://www.facebook.com/groups/autisme.alsace/posts/44556677",
    notes: "Famille désemparée. L'IME pousse vers une hospitalisation en psychiatrie par défaut si aucune MAS n'est trouvée."
  },
  {
    id: "post-8",
    type: "FO",
    status: "Contacted",
    priority: "Low",
    date: "2026-05-20",
    region: "Pays de la Loire",
    title: "Recherche Foyer de Vie pour rentrée 2026 - Maxime, 26 ans",
    description: "Maxime a 26 ans, il présente un handicap moteur cérébral (I.M.C.) stabilisé avec déplacements en fauteuil roulant électrique. Il recherche une place en Foyer de Vie / Foyer Occupationnel adapté PMR avec animations dynamiques en Loire-Atlantique (44).",
    handicap: "Infirmité Motrice Cérébrale",
    age: 26,
    familyMember: "Maxime",
    contactName: "Pierre-Yves Renaud (Père)",
    contactPhone: "+33 6 15 98 76 54",
    contactEmail: "py.renaud.nantes@gmail.com",
    contactSocial: "https://forum.apf-francehandicap.org/viewtopic.php?f=12&t=4567",
    notes: "Contacté par email pour leur proposer la liste des établissements gérés par l'APF du 44."
  },
  {
    id: "post-9",
    type: "FAM",
    status: "Spot Secured",
    priority: "Medium",
    date: "2026-05-18",
    region: "Bretagne",
    title: "Recherche FAM handicap psychique - Chloé, 33 ans",
    description: "Recherche place en Foyer d'Accueil Médicalisé spécialisé handicap psychique / schizophrénie stabilisée pour ma fille Chloé, 33 ans. Besoins de repères quotidiens rassurants et d'une surveillance infirmière pour le traitement. Secteur d'Ille-et-Vilaine (35) ou Morbihan (56).",
    handicap: "Handicap Psychique",
    age: 33,
    familyMember: "Chloé",
    contactName: "Françoise Le Gall (Mère)",
    contactPhone: "+33 2 99 65 43 21",
    contactEmail: "francoise.legall.rennes@orange.fr",
    contactSocial: "https://www.facebook.com/groups/unafam.bretagne/posts/11223344",
    notes: "Bonne nouvelle : Chloé a obtenu une place au FAM de Redon ! Entrée prévue le 15 juin. Dossier clôturé positivement."
  },
  {
    id: "post-10",
    type: "MAS",
    status: "New",
    priority: "High",
    date: "2026-05-17",
    region: "Normandie",
    title: "Urgence absolue: Place MAS après décès de l'aidant principal - Kevin, 27 ans",
    description: "Suite au décès brutal du père et aidant principal de Kevin, 27 ans, atteint du syndrome de Rett, nous recherchons une admission d'urgence en MAS en Seine-Maritime (76). Actuellement accueilli de manière très temporaire à l'hôpital local.",
    handicap: "Syndrome de Rett",
    age: 27,
    familyMember: "Kevin",
    contactName: "Mme Brigitte Legrand (Assistante Sociale Hôpital)",
    contactPhone: "+33 2 35 70 80 90",
    contactEmail: "b.legrand@ch-rouen.fr",
    contactSocial: "https://www.linkedin.com/posts/brigitte-legrand-as_urgence-placement-handicap-rett-activity-71239847",
    notes: "Dossier prioritaire d'urgence ARS envoyé. Suivi quotidien avec l'assistante sociale."
  },
  {
    id: "post-11",
    type: "FO",
    status: "Waiting List",
    priority: "Medium",
    date: "2026-05-15",
    region: "Centre-Val de Loire",
    title: "Recherche Foyer de Vie pour réorientation - Mathieu, 34 ans",
    description: "Mathieu est actuellement logé chez sa grand-mère âgée qui ne peut plus s'en occuper au quotidien. Mathieu est autonome pour les actes simples, présente une déficience intellectuelle légère à moyenne. Orientation Foyer de Vie acquise pour le Loiret (45).",
    handicap: "Déficience Intellectuelle",
    age: 34,
    familyMember: "Mathieu",
    contactName: "Georgette Bernard (Grand-mère)",
    contactPhone: "+33 2 38 12 34 00",
    contactEmail: "georgette.bernard45@free.fr",
    contactSocial: "https://www.facebook.com/groups/entraide.handicap.loiret/posts/8829102",
    notes: "Placé sur la liste d'attente globale de l'ADAPEI 45. Recherche active d'une colocation adaptée en parallèle."
  },
  {
    id: "post-12",
    type: "FAM",
    status: "New",
    priority: "Medium",
    date: "2026-05-14",
    region: "Bourgogne-Franche-Comté",
    title: "Demande de FAM pour jeune adulte - Lucie, 21 ans (Double diagnostic)",
    description: "Lucie présente une déficience intellectuelle associée à des troubles psychiatriques (Double Diagnostic). Sortie d'IME prévue cet été. Orientation FAM notifiée par la MDPH de Côte d'Or. Recherche place en Bourgogne.",
    handicap: "Double Diagnostic (DI + Psy)",
    age: 21,
    familyMember: "Lucie",
    contactName: "Patricia Roy (Mère)",
    contactPhone: "+33 6 77 88 99 00",
    contactEmail: "patricia.roy21@neuf.fr",
    contactSocial: "https://www.facebook.com/groups/double-diagnostic-france/posts/3294820",
    notes: "Prise de contact par email. La maman cherche des adresses de FAM spécialisés double diagnostic."
  }
];

// Helper to write logs for the simulation terminal
const crawlerLogTemplates = [
  { level: "info", text: "Initializing AGIS crawler engine v1.4.2..." },
  { level: "info", text: "Target queries: ['Maison d\\'accueil specialisee', 'Foyer d\\'accueil medicalise', 'Foyer de vie', 'Foyer occupationnel', 'place MAS', 'place FAM', 'place FO']" },
  { level: "search", text: "Scanning Facebook Groups (Autisme France, Polyhandicap Aidants, Association Trisomie)..." },
  { level: "success", text: "Found matching post on 'Aidants Handicap IDF': 'Recherche place MAS en urgence...' (Thomas, 22 ans)" },
  { level: "search", text: "Scanning public forum 'Doctissimo - Section Handicap'..." },
  { level: "success", text: "Extracted thread: 'Recherche Foyer de Vie dans le Nord' by user ClaireL59" },
  { level: "search", text: "Crawling LinkedIn posts with hashtag #handicap #foyerdevie #placedisponible..." },
  { level: "info", text: "Scanning regional ARS directories for newly declared accommodation spots..." },
  { level: "warning", text: "Rate limit hit on Twitter Search API. Cooling down for 15 seconds..." },
  { level: "search", text: "Scanning Reddit community r/france_handicap..." },
  { level: "info", text: "Database synchronization complete. 12 active listings, 0 pending verification." }
];

// Export standard mock listings if needed by standard script imports
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { initialPostings, crawlerLogTemplates };
}
